"""change pokemon id to false unique

Revision ID: 67a45e1aaf85
Revises: 50ca632acc0b
Create Date: 2024-03-06 14:57:55.024660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a45e1aaf85'
down_revision = '50ca632acc0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_constraint('pokemon_pokemon_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.create_unique_constraint('pokemon_pokemon_id_key', ['pokemon_id'])

    # ### end Alembic commands ###
